plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "G:\\擎科生物\\销综系统\\260427商务新规划\\原型"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]